language: python
dist: xenial
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x

matrix:
  include:
    - python: '3.5'
      env:
        - TOXENV=py35
    - python: '3.6'
      env:
        - TOXENV=py36
    - python: '3.7'
      env:
        - TOXENV=py37
    - python: '3.8'
      env:
        - TOXENV=py38
    - python: '3.7'
      env:
        - TOXENV=pillow3.x
    - python: '3.7'
      env:
        - TOXENV=pillow4.x
    - python: '3.7'
      env:
        - TOXENV=pillow5.x
    - python: '3.7'
      env:
        - TOXENV=pillow6.x
    - python: '3.7'
      env:
        - TOXENV=pillow7.x

install:
  - sudo apt-get install fonts-ipafont-gothic libjpeg8-dev libfreetype6-dev
  - pip install -U docutils tox

script:
  - tox -- -v
